[workspace.package]
version = "0.0.1"
edition = "2024"
license = "Apache-2.0"


[workspace]
members = ["src/app", "src/mcp"]
resolver = "3"


[workspace.dependencies]
mcp = {path = "src/mcp"}
app = {path = "src/app"}

    